CREATE TABLE WAREHOUSE (W_ID INT, W_NAME CHAR(10), W_STREET_1 CHAR(20), W_STREET_2 CHAR(20), W_CITY CHAR(20), W_STATE CHAR(2), W_ZIP CHAR(9), W_TAX FLOAT, W_YTD FLOAT, PRIMARY KEY(W_ID));

CREATE TABLE DISTRICT (D_ID INT, D_W_ID INT, D_NAME CHAR(10), D_STREET_1 CHAR(20), D_STREET_2 CHAR(20), D_CITY CHAR(20), D_STATE CHAR(2), D_ZIP CHAR(9), D_TAX FLOAT, D_YTD FLOAT, D_NEXT_O_ID INT, PRIMARY KEY(D_W_ID, D_ID));
CREATE TABLE ITEM (I_ID INT, I_IM_ID INT, I_NAME CHAR(24), I_PRICE FLOAT, I_DATA CHAR(50), PRIMARY KEY(I_ID));


CREATE TABLE CUSTOMER (C_ID INT, C_D_ID INT, C_W_ID INT, C_FIRST CHAR(16), C_MIDDLE CHAR(2), C_LAST CHAR(16), C_STREET_1 CHAR(20), C_STREET_2 CHAR(20), C_CITY CHAR(20), C_STATE CHAR(2), C_ZIP CHAR(9), C_PHONE CHAR(16), C_SINCE CHAR(30), C_CREDIT CHAR(2), C_CREDIT_LIM FLOAT, C_DISCOUNT FLOAT, C_BALANCE FLOAT, C_YTD_PAYMENT FLOAT, C_PAYMENT_CNT INT, C_DELIVERY_CNT INT, C_DATA CHAR(50), PRIMARY KEY(C_W_ID, C_D_ID, C_ID));

CREATE TABLE HISTORY (H_C_ID INT, H_C_D_ID INT, H_C_W_ID INT, H_D_ID INT, H_W_ID INT, H_DATE CHAR(20), H_AMOUNT FLOAT, H_DATA CHAR(24));
CREATE TABLE STOCK (S_I_ID INT, S_W_ID INT, S_QUANTITY INT, S_DIST_01 CHAR(24), S_DIST_02 CHAR(24), S_YTD INT, S_ORDER_CNT INT, S_REMOTE_CNT INT, S_DATA CHAR(50), PRIMARY KEY(S_W_ID, S_I_ID));
CREATE TABLE ORDERS (O_ID INT, O_C_ID INT, O_D_ID INT, O_W_ID INT, O_ENTRY_D CHAR(20), O_CARRIER_ID INT, O_OL_CNT INT, O_ALL_LOCAL INT, PRIMARY KEY(O_W_ID, O_D_ID, O_ID, O_C_ID));


CREATE TABLE NEW_ORDER (NO_O_ID INT, NO_D_ID INT, NO_W_ID INT, PRIMARY KEY(NO_D_ID,NO_W_ID,NO_O_ID));

CREATE TABLE ORDER_LINE ( OL_O_ID INT, OL_D_ID INT, OL_W_ID INT, OL_NUMBER INT, OL_I_ID INT, OL_SUPPLY_W_ID INT, OL_DELIVERY_D CHAR(30), OL_QUANTITY INT, OL_AMOUNT FLOAT, OL_DIST_INFO CHAR(24), PRIMARY KEY(OL_W_ID, OL_D_ID, OL_O_ID, OL_NUMBER));
